### ISSUE TITLE
SRG Message: The Service is temporarily unavailable

### ISSUE THREAD

**Issue by baerengraben** [baerengraben/ioBroker.swiss-weather-api#24]
It may happen that SRG takes the service out of service for a short time (probably for maintenance). Then the following error will be reported by SRG:

2021-01-18 04:33:33.411 - error: swiss-weather-api.0 (12557) Response has announced an error: The Service is temporarily unavailable

Currently, only the date can be used to see how up-to-date the data is. But we should include this info as a status object in ioBroker. Idea:
If weather info is older than the "poll interval", a status "data outdated" should be set to true.

**Comment by UncleSamSwiss** [comment]
I guess the API is unavailable again. At least I'm not getting any data since yesterday.

There are two other things you can (and probably should) do:
- The state `info.connection` should always report of the connection to the service is ok or not. Like this, the icon next to the adapter instance will be yellow instead of green.
- every state has also a quality information (simply called `q`) you may set all states' quality to a meaningful value (see developer documentation for more details)

**Comment by baerengraben** [comment]
Thanks for these tips :)

...And yes, currently the service does not provide any data right now :(

**Comment by Matt77CHE** [comment]
Still no data.... this makes this adapter unfortunately unusable, as SRG-SSR is once again unreliable

**Comment by baerengraben** [comment]
Please use the new Adapter Version 0.9.0. This Adapter uses the new SRF Weather API (https://developer.srgssr.ch/apis/srf-weather).
 
As I can see today, the old  weather API (https://developer.srgssr.ch/apis/weather-api-commercial) is not available (again). But the new SRF Weather API (with Freemium subscription) is working. So i guess it is best to change to Version > 0.9.0 as quick as possible...

**Comment by baerengraben** [comment]
Partly resolved with version 0.9.1.
- Adapter Info State is handled now. 
- q Infos for each datapoint still not available

**Comment by baerengraben** [comment]
instead of generating a q for each data point, with Version 0.9.4 I added the following data points, which inform about the status of the adapter:

- swiss-weather-api.0.info.connection
- swiss-weather-api.0.info.lastrun
