### ISSUE TITLE
API will be deprecated in 3 Months => New API https://developer.srgssr.ch/apis/srf-weather

### ISSUE THREAD

**Issue by baerengraben** [baerengraben/ioBroker.swiss-weather-api#35]
SRG informs that the current API will run until the end of July 2021. Until then, the adapter must be rewritten to the new version: https://developer.srgssr.ch/apis/srf-weather

**Comment by baerengraben** [comment]
Good news. Now 50 queries per day will be possible with a freemium subscription. With this, the weather can be queried every half hour (which is also the default setting of the adapter).

**Comment by baerengraben** [comment]
Closed with Version 0.9.0

**Comment by cdellasanta** [comment]
👍  Many thanks fr your work, seems to work, but of course I've to adapt many of the probe-points to the new paths.

Only one thing I don't understand @baerengraben: Why did you jumped from version `0.3.2` to `0.9.0`?  
Correct would have been to go for a mayor version, ergo `1.0.0` (because of course there is no backwards-compatibility with the previous one).
